"""add platform support for multi-im integration

Revision ID: 553d78018b0a
Revises: 5eaa11196095
Create Date: 2026-01-28 11:28:40.285140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553d78018b0a'
down_revision: Union[str, Sequence[str], None] = '5eaa11196095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add platform column as nullable with default value
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=20), nullable=True, server_default='wecom', comment='平台类型: wecom, slack, telegram, discord'))
        batch_op.add_column(sa.Column('target_url', sa.String(length=500), nullable=True, comment='转发目标 URL (完整地址，推荐使用)'))
        batch_op.add_column(sa.Column('platform_config', sa.Text(), nullable=True, comment='平台特定配置（JSON 格式），例如 Slack: {bot_token, signing_secret}'))
        batch_op.alter_column('url_template',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.create_index('idx_chatbots_platform', ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbots_platform'), ['platform'], unique=False)
    
    # Step 2: Update existing rows to have platform='wecom'
    op.execute("UPDATE chatbots SET platform='wecom' WHERE platform IS NULL")
    
    # Step 3: Make platform column non-nullable
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.alter_column('platform',
               existing_type=sa.String(length=20),
               nullable=False)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_project_id', sa.String(length=100), nullable=True, comment='当前使用的项目 ID'))
        batch_op.add_column(sa.Column('project_config_id', sa.Integer(), nullable=True, comment='关联的项目配置 ID (外键)'))
        batch_op.create_index('idx_user_session_project', ['current_project_id'], unique=False)
        batch_op.create_foreign_key(None, 'user_project_configs', ['project_config_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_user_session_project')
        batch_op.drop_column('project_config_id')
        batch_op.drop_column('current_project_id')

    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbots_platform'))
        batch_op.drop_index('idx_chatbots_platform')
        batch_op.alter_column('url_template',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('platform_config')
        batch_op.drop_column('target_url')
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
