"""Add platform and platform_config fields for multi-IM support

Revision ID: 6ef6b090f545
Revises: 5eaa11196095
Create Date: 2026-01-29 14:58:08.004521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef6b090f545'
down_revision: Union[str, Sequence[str], None] = '5eaa11196095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=20), nullable=False, comment='平台类型: wecom, discord, slack, wecom-intelligent'))
        batch_op.add_column(sa.Column('platform_config', sa.Text(), nullable=True, comment='平台特定配置（JSON 格式），例如智能机器人: {support_stream, support_template_card}'))
        batch_op.create_index('idx_chatbots_platform', ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbots_platform'), ['platform'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbots_platform'))
        batch_op.drop_index('idx_chatbots_platform')
        batch_op.drop_column('platform_config')
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
