"""add_outbound_message_contexts_table

Revision ID: e919da388f6f
Revises: 798deed41e28
Create Date: 2026-03-22 19:55:28.333495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e919da388f6f'
down_revision: Union[str, Sequence[str], None] = '798deed41e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_message_contexts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=False, comment='企微消息 ID'),
    sa.Column('task_id', sa.String(length=50), nullable=True, comment='TaskItem ID（来自任务队列）'),
    sa.Column('agent_id', sa.String(length=100), nullable=True, comment='发送消息的 Agent ID'),
    sa.Column('session_id', sa.String(length=100), nullable=True, comment='Agent 会话 ID'),
    sa.Column('bot_key', sa.String(length=100), nullable=False, comment='发送消息使用的 Bot Key'),
    sa.Column('chat_id', sa.String(length=200), nullable=False, comment='目标 Chat ID（群ID或私聊ID）'),
    sa.Column('content_preview', sa.String(length=200), nullable=True, comment='消息内容预览（前 200 字符）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending（待回复）/ replied（已回复）/ expired（已过期）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('replied_at', sa.DateTime(), nullable=True, comment='回复时间'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间（默认创建后 24 小时）'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbound_message_contexts', schema=None) as batch_op:
        batch_op.create_index('idx_outbound_ctx_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_outbound_ctx_message_id', ['message_id'], unique=False)
        batch_op.create_index('idx_outbound_ctx_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_message_contexts_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbound_message_contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbound_message_contexts_message_id'))
        batch_op.drop_index('idx_outbound_ctx_status')
        batch_op.drop_index('idx_outbound_ctx_message_id')
        batch_op.drop_index('idx_outbound_ctx_expires_at')

    op.drop_table('outbound_message_contexts')
    # ### end Alembic commands ###
